### ISSUE TITLE
trVAE error in `self.cvae_model.evaluate`

### ISSUE THREAD

**Issue by LuckyMD** [theislab/trVAE#10]
Hey @Naghipourfar @M0hammadL ,

I'm running trVAE as part of our benchmarking (PR [here](https://github.com/theislab/scib/pull/136)), and I'm getting the following error:

```
|Traceback (most recent call last):
  File "scripts/runIntegration.py", line 69, in <module>
    runIntegration(file, out, run, hvg, batch)
  File "scripts/runIntegration.py", line 30, in runIntegration
    integrated = method(adata, batch)
  File "/mnt/home/icb/malte.luecken/benchmarking_data_integration/Benchmarking_data_integration/scIB/integration.py", line 70, in runTrVae
    save=False,
  File "/home/icb/daniel.strobl/miniconda3/envs/benchmarking_data_integration_dev/lib/python3.7/site-packages/trvae/models/_trvae.py", line 830, in train
    verbose)
  File "/home/icb/daniel.strobl/miniconda3/envs/benchmarking_data_integration_dev/lib/python3.7/site-packages/trvae/models/_trvae.py", line 771, in _train_on_batch
    valid_loss, valid_recon_loss, valid_mmd_loss = self.cvae_model.evaluate(x_valid, y_valid, verbose=0)
ValueError: not enough values to unpack (expected 3, got 0)|
```

**Comment by M0hammadL** [comment]
Hey @LuckyMD  it seems in your code you have set `train_size=1.0` that means there is no validation data for
the model to validate the results. please set it to `0.9`. 
https://github.com/theislab/scib/blob/c92622a3ca57e922f7533356ff7631d944ca9bd1/scIB/integration.py#L64

**Comment by LuckyMD** [comment]
okay, so no training on the full dataset even for batch removal?

**Comment by LuckyMD** [comment]
will test to see if this works.
